server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      # --- CONFIGURACIÓN GLOBAL DE CORS ---
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      # ------------------------------------
      routes:
        # 1. Ruta para el Swagger de Usuarios
        - id: swagger-usuarios
          uri: http://api-usuarios:8080
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html

        # 2. Ruta para Proyectos
        - id: gestion-proyectos
          uri: http://api-proyectos:8081
          predicates:
            - Path=/api/proyectos/**
          filters:
            - StripPrefix=1

        # 3. Ruta para Usuarios y Auth
        - id: gestion-usuarios
          uri: http://api-usuarios:8080
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=1

        # 4. RUTA: Analytics (Opcional)
        #- id: api-analytics
          #uri: http://api-analytics:8080
          #predicates:
            #- Path=/api/analytics/**
          #filters:
            #- StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway